// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"net"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Interface struct {
	ID         int32  `json:"id"`
	Privatekey string `json:"privatekey"`
	Address    string `json:"address"`
	Listenport int32  `json:"listenport"`
}

type IpAssignment struct {
	NetworkID int32       `json:"network_id"`
	UserID    pgtype.Int4 `json:"user_id"`
	Ip        netip.Addr  `json:"ip"`
}

type Network struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Cidr      net.IPNet        `json:"cidr"`
	OwnerID   pgtype.Int4      `json:"owner_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type NetworkMember struct {
	UserID    int32            `json:"user_id"`
	NetworkID int32            `json:"network_id"`
	JoinedAt  pgtype.Timestamp `json:"joined_at"`
}

type Peer struct {
	ID          int32       `json:"id"`
	InterfaceID pgtype.Int4 `json:"interface_id"`
	Name        string      `json:"name"`
	Publickey   string      `json:"publickey"`
	Allowedips  string      `json:"allowedips"`
}

type User struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
