// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subnets.sql

package repository

import (
	"context"
	"net"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkIpInNetwork = `-- name: CheckIpInNetwork :one
SELECT id, name, cidr, owner_id, created_at 
FROM networks
WHERE $1 << cidr
`

func (q *Queries) CheckIpInNetwork(ctx context.Context, cidr net.IPNet) (Network, error) {
	row := q.db.QueryRow(ctx, checkIpInNetwork, cidr)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createNetwork = `-- name: CreateNetwork :one
INSERT INTO networks (name, cidr, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, cidr, owner_id, created_at
`

type CreateNetworkParams struct {
	Name    string      `json:"name"`
	Cidr    net.IPNet   `json:"cidr"`
	OwnerID pgtype.Int4 `json:"owner_id"`
}

func (q *Queries) CreateNetwork(ctx context.Context, arg CreateNetworkParams) (Network, error) {
	row := q.db.QueryRow(ctx, createNetwork, arg.Name, arg.Cidr, arg.OwnerID)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email)
VALUES ($1, $2)
RETURNING id, username, email, created_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getNetworkByOwner = `-- name: GetNetworkByOwner :one
SELECT id, name, cidr, owner_id, created_at
FROM networks
WHERE owner_id = $1
LIMIT 1
`

func (q *Queries) GetNetworkByOwner(ctx context.Context, ownerID pgtype.Int4) (Network, error) {
	row := q.db.QueryRow(ctx, getNetworkByOwner, ownerID)
	var i Network
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cidr,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getSubnetsWithPeers = `-- name: GetSubnetsWithPeers :many
SELECT i.id AS interface_id, i.address, i.listenPort,
       p.id AS peer_id, p.name, p.publicKey, p.allowedIPs
FROM INTERFACE i
LEFT JOIN PEER p ON p.interface_id = i.id
`

type GetSubnetsWithPeersRow struct {
	InterfaceID int32       `json:"interface_id"`
	Address     string      `json:"address"`
	Listenport  int32       `json:"listenport"`
	PeerID      pgtype.Int4 `json:"peer_id"`
	Name        pgtype.Text `json:"name"`
	Publickey   pgtype.Text `json:"publickey"`
	Allowedips  pgtype.Text `json:"allowedips"`
}

func (q *Queries) GetSubnetsWithPeers(ctx context.Context) ([]GetSubnetsWithPeersRow, error) {
	rows, err := q.db.Query(ctx, getSubnetsWithPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubnetsWithPeersRow
	for rows.Next() {
		var i GetSubnetsWithPeersRow
		if err := rows.Scan(
			&i.InterfaceID,
			&i.Address,
			&i.Listenport,
			&i.PeerID,
			&i.Name,
			&i.Publickey,
			&i.Allowedips,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworkUsers = `-- name: ListNetworkUsers :many
SELECT u.id, u.username, u.email, u.created_at
FROM users u
JOIN network_members nm ON nm.user_id = u.id
WHERE nm.network_id = $1
`

func (q *Queries) ListNetworkUsers(ctx context.Context, networkID int32) ([]User, error) {
	rows, err := q.db.Query(ctx, listNetworkUsers, networkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworks = `-- name: ListNetworks :many
SELECT id, name, cidr, owner_id, created_at
FROM networks
ORDER BY created_at DESC
`

func (q *Queries) ListNetworks(ctx context.Context) ([]Network, error) {
	rows, err := q.db.Query(ctx, listNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Network
	for rows.Next() {
		var i Network
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cidr,
			&i.OwnerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerHasNetwork = `-- name: OwnerHasNetwork :one
SELECT EXISTS (
    SELECT 1 FROM networks WHERE owner_id = $1
) AS has_network
`

func (q *Queries) OwnerHasNetwork(ctx context.Context, ownerID pgtype.Int4) (bool, error) {
	row := q.db.QueryRow(ctx, ownerHasNetwork, ownerID)
	var has_network bool
	err := row.Scan(&has_network)
	return has_network, err
}
